// Code generated by open_plc_cube_ide/IAPServer/generate_fixed_password.sh
// from IAPServer/iap_fixed_password.txt. DO NOT EDIT -- edit that file and
// re-run the generator instead.
package iapcrypto

const FixedPassword = "IAP-FIXED-PASSWORD-TEST-ONLY-CHANGE-ME"
